### ISSUE TITLE
JAVA-Start bei Testrunner klappt nicht, bleibt aber grün

### ISSUE THREAD

**Issue by foto-andreas** [set-de/jenkins_ws#38]
```
Error executing testcases on execution-system local_linux
19 	java.io.IOException: Cannot run program "java" (in directory "/tmp/posyH0/program/POSY-Storage"): error=2, Datei oder Verzeichnis nicht gefunden
20 		at java.lang.ProcessBuilder.start(ProcessBuilder.java:1047)
21 		at de.setsoftware.posy.testrunner.model.WebAppProcess.<init>(WebAppProcess.java:106)
22 		at de.setsoftware.posy.testrunner.model.WebAppProcess.startProcessInPosyPath(WebAppProcess.java:169)
23 		at de.setsoftware.posy.testrunner.model.ComponentTestcaseExecutor.startWebAppProcess(ComponentTestcaseExecutor.java:58)
24 		at de.setsoftware.posy.testrunner.model.LocalTestcaseExecutor.doStartWebApp(LocalTestcaseExecutor.java:354)
25 		at de.setsoftware.posy.testrunner.model.TestcaseExecutor.startWebapp(TestcaseExecutor.java:503)
26 		at de.setsoftware.posy.testrunner.model.TestcaseExecutor.restartWebapp(TestcaseExecutor.java:747)
27 		at de.setsoftware.posy.testrunner.model.TestcaseExecutor.access$000(TestcaseExecutor.java:59)
28 		at de.setsoftware.posy.testrunner.model.TestcaseExecutor$3.doExecute(TestcaseExecutor.java:709)
29 		at de.setsoftware.posy.testrunner.model.TestcaseExecutor$3.doExecute(TestcaseExecutor.java:705)
30 		at de.setsoftware.posy.testrunner.helper.RetryAction.execute(RetryAction.java:48)
31 		at de.setsoftware.posy.testrunner.model.TestcaseExecutor.restartWebappWithRetry(TestcaseExecutor.java:705)
32 		at de.setsoftware.posy.testrunner.model.Maintestsequence.abstractRun(Maintestsequence.java:41)
33 		at de.setsoftware.posy.testrunner.model.Maintestsequence.abstractRun(Maintestsequence.java:19)
34 		at de.setsoftware.posy.testrunner.model.AbstractTestcase.run(AbstractTestcase.java:161)
35 		at de.setsoftware.posy.testrunner.model.TestcaseRunner.runTestsuite(TestcaseRunner.java:60)
36 		at de.setsoftware.posy.testrunner.TestrunnerMain.main(TestrunnerMain.java:200)
37 	Caused by: java.io.IOException: error=2, Datei oder Verzeichnis nicht gefunden
38 		at java.lang.UNIXProcess.forkAndExec(Native Method)
39 		at java.lang.UNIXProcess.<init>(UNIXProcess.java:186)
40 		at java.lang.ProcessImpl.start(ProcessImpl.java:130)
41 		at java.lang.ProcessBuilder.start(ProcessBuilder.java:1028)
42 		... 16 more
43 	Testrunner for cluster local_linux exited with rc 99.

```

**Comment by soenkekueper** [comment]
Das liegt darin begründet, dass in dem Testrunner-Plugin alle RCs beim Starten des Testrunners abgefangen und verarbeitet werden. I.e. bei allen RCs != 0 wird der Status auf "FAILURE" gesetzt, aber keine Exception geworfen (Was den Build-Step rot machen würde). Das kann durch Anpassung des Steps erfolgen, in dem dieser ein eigener Workflow-Step ist und nicht über den generischen Step ausgeführt wird.
