### ISSUE TITLE
Remote Unit-Tests mit NPE z.B. #84

### ISSUE THREAD

**Issue by foto-andreas** [set-de/jenkins_ws#45]
```
01:01:32.763 [UnitTests AIX] AN UNCAUGHT EXCEPTION OCCURRED in thread main
01:01:32.763 [UnitTests AIX] de.setsoftware.stdlib.remoteChannel.Logger INFO Caught an exception, leaving main loop due to Socket closed
01:01:32.763 [UnitTests AIX] java.lang.NullPointerException
01:01:32.763 [UnitTests AIX] 	at java.lang.String.replace(String.java:2180)
01:01:32.763 [UnitTests AIX] 	at de.setsoftware.posy.testrunner.properties.PropertiesVariableResolver.setUser(PropertiesVariableResolver.java:45)
01:01:32.763 [UnitTests AIX] 	at de.setsoftware.posy.testrunner.properties.system.CommonSystemPropertiesImpl.getInstallDir(CommonSystemPropertiesImpl.java:115)
01:01:32.764 [UnitTests AIX] 	at de.setsoftware.posy.testrunner.model.TestcaseFileManager.getInstallDir(TestcaseFileManager.java:136)
01:01:32.764 [UnitTests AIX] 	at de.setsoftware.posy.testrunner.model.TestcaseFileManager.getProgramDir(TestcaseFileManager.java:485)
01:01:32.764 [UnitTests AIX] 	at de.setsoftware.posy.testrunner.model.TestcaseExecutor.getProgramDir(TestcaseExecutor.java:937)
01:01:32.764 [UnitTests AIX] 	at de.setsoftware.posy.testrunner.model.RemoteTestcaseExecutor.getComponentPath(RemoteTestcaseExecutor.java:468)
01:01:32.764 [UnitTests AIX] 	at de.setsoftware.posy.testrunner.model.RemoteTestcaseExecutor.getRemoteWebAppPath(RemoteTestcaseExecutor.java:429)
01:01:32.764 [UnitTests AIX] 	at de.setsoftware.posy.testrunner.model.PosixTestcaseExecutor$9.stopRemoteAppByInitScript(PosixTestcaseExecutor.java:470)
01:01:32.764 [UnitTests AIX] 	at de.setsoftware.posy.testrunner.model.PosixTestcaseExecutor$9.doExecute(PosixTestcaseExecutor.java:459)
01:01:32.764 [UnitTests AIX] 	at de.setsoftware.posy.testrunner.model.RemoteTestcaseExecutor$SSHCommand.execute(RemoteTestcaseExecutor.java:58)
01:01:32.764 [UnitTests AIX] 	at de.setsoftware.posy.testrunner.model.PosixTestcaseExecutor.cleanUpPreviousServerProcesses(PosixTestcaseExecutor.java:477)
01:01:32.764 [UnitTests AIX] 	at de.setsoftware.posy.testrunner.model.TestcaseExecutor.installPOSY(TestcaseExecutor.java:801)
01:01:32.764 [UnitTests AIX] 	at de.setsoftware.posy.testrunner.model.TestcaseExecutor$4.doExecute(TestcaseExecutor.java:780)
01:01:32.765 [UnitTests AIX] 	at de.setsoftware.posy.testrunner.model.TestcaseExecutor$4.doExecute(TestcaseExecutor.java:1)
01:01:32.765 [UnitTests AIX] 	at de.setsoftware.posy.testrunner.helper.RetryAction.execute(RetryAction.java:48)
01:01:32.765 [UnitTests AIX] 	at de.setsoftware.posy.testrunner.model.TestcaseExecutor.installPosyWithRetry(TestcaseExecutor.java:791)
01:01:32.765 [UnitTests AIX] 	at de.setsoftware.posy.testrunner.model.PosixTestcaseExecutor.runJUnit(PosixTestcaseExecutor.java:264)
01:01:32.765 [UnitTests AIX] 	at de.setsoftware.posy.testrunner.model.TestcaseRunner.runJUnit(TestcaseRunner.java:109)
01:01:32.765 [UnitTests AIX] 	at de.setsoftware.posy.testrunner.UnitMain.main(UnitMain.java:92)
01:01:32.765 [UnitTests AIX] 
01:01:32.765 [UnitTests AIX] JVM will be terminated
01:01:32.765 [UnitTests AIX] de.setsoftware.stdlib.common.Logger INFO Received shutdown event...
01:01:32.766 [UnitTests AIX] de.setsoftware.stdlib.common.Logger INFO ShutdownExecutableManager: performing shutdown
01:01:32.025 [UnitTests ZOS] Failed in branch UnitTests ZOS
[Pipeline] [UnitTests Solaris] }
[Pipeline] [UnitTests AIX] }
[Pipeline] [UnitTests Solaris] // dir
```

**Comment by foto-andreas** [comment]
Testrunner-User war nicht gesetzt. Nachgetragen.
